name: first workflow

env:
  WORKFLOW_VAR: "a workflow var"

on:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: firstJob script
        shell: bash
        run: echo Hello world! 1st job
      - name: checkout the repo
        uses: actions/checkout@v3
      - name: greet a user
        id: greetings
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Nikos"
      - name: the greeting time
        run: |
          echo "time: ${{steps.greetings.output.time}}"
          

        
  secondjob:
    runs-on: ubuntu-latest
    needs: firstjob
    env:
      JOB_VAR: "a job var"
    steps:
      - name: secondJob script
        env:
          STEP_VAR: "a step var"
        shell: bash
        run: |
          echo WORKFLOW_VAR
          echo JOB_VAR
          echo STEP_VAR
          echo "a secret ${{ secrets.SOME_SECRET}}"
