name: first workflow

on:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: firstJob script
        shell: bash
        run: echo Hello world! 1st job
      - name: checkout the repo
        uses: action/checkout@v3
      - name: greet a user
        id: greetings
        uses: action/hello-world-javascript-action@main
        with:
          who-to-greet: "Nikos"
      - name: the greeting time
        run: |
          echo "time: ${{steps.greetings.output.time}}"
          

        
  secondjob:
    runs-on: ubuntu-latest
    steps:
      - name: secondJob script
        shell: bash
        run: |
          echo 2nd job 1st line
          echo 2nd job 2nd line
